spring:
  application:
    name: meeting-manager-service
  redis:
    host: redis
    port: 6379
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 8
  cache:
    type: redis
    redis:
      time-to-live: 30
      cache-null-values: false
  kafka:
    bootstrap-servers: broker:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/obss-scheduler
  datasource:
    hikari:
      auto-commit: false
    url: "jdbc:postgresql://postgres:5432/postgres"
    username: postgres
    password: postgres
    dbName: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8089
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka

topics:
  notification: notification-topic
  email: notification-email
  zoom-error: zoom-error

feign:
  client:
    config:
      default:
        errorDecoder: tr.com.obss.meetingmanager.feigns.FeignClientErrorDecoder

resilience4j:
  retry:
    instances:
      googleEvent:
        maxRetryAttempts: 3
        waitDuration: 3s

keycloak:
  auth-server-url: http://keycloak:8080/auth
  realm: obss-scheduler
  resource: schedule-app-be
  credentials:
    secret: d2cff314-7bbd-42f8-8c29-743cfef3827c