spring:
  application:
    name: meeting-manager-service
  redis:
    host: localhost
    port: 6379
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 8
  cache:
    type: redis
    redis:
      time-to-live: 30
      cache-null-values: false
  kafka:
    bootstrapservers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/auth/realms/obss-scheduler
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: postgres
    dbName: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8089
eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
topics:
  notification: notification-topic
#resilience4j:
#  retry:
#    instances:
#      googleService:
#        maxRetryAttempts: 3
#        waitDuration: 2s
##        resultPredicate: tr.com.obss.meetingmanager.resilliance4j.predicates.ConditionalRetryPredicate
#feign:
#  client:
#    config:
#      default:
#        errorDecoder: tr.com.obss.meetingmanager.feigns.DrmClientErrorDecoder
#          retryExceptions:
#            - java.lang.Exception
#            -