spring:
  application:
    name: meeting-manager-service
  kafka:
    bootstrapservers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/auth/realms/obss-scheduler
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: postgres
    dbName: meeting-manager
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8089

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
topics:
  notification: notification-topic
#resilience4j:
#  retry:
#    instances:
#      googleService:
#        maxRetryAttempts: 3
#        waitDuration: 2s
##        resultPredicate: tr.com.obss.meetingmanager.resilliance4j.predicates.ConditionalRetryPredicate
#feign:
#  client:
#    config:
#      default:
#        errorDecoder: tr.com.obss.meetingmanager.feigns.DrmClientErrorDecoder
#          retryExceptions:
#            - java.lang.Exception
#            -