spring:
  application:
    name: meeting-manager-service
  kafka:
    bootstrapservers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/auth/realms/obss-scheduler
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: postgres
    dbName: meeting-manager
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8089

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
topics:
  notification: notification-topic
